import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import { getLocale } from "next-intl/server";

import { Providers } from "@/providers";

import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Frontline",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <html lang={locale}>
      {/* <head>
        <script
          crossOrigin="anonymous"
          src="//unpkg.com/react-scan/dist/auto.global.js"
        />
      </head> */}
      <body className={`${GeistSans.className} antialiased`} suppressHydrationWarning>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
